<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SocketLabs.Tests</RootNamespace>
    <AssemblyName>SocketLabs.Tests</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyTitle>SocketLabs.Tests</AssemblyTitle>
	<IsPackable>false</IsPackable>
	<Product>SocketLabs.Tests</Product>
    <Copyright>Copyright © 2018-2025 SocketLabs Acquisition LLC</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.1" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.2" />
    <PackageReference Include="System.ValueTuple" Version="4.6.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.8.3" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.8.3" />
    <PackageReference Include="coverlet.collector" Version="10.0.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SocketLabs\SocketLabs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ClientTests\" />
  </ItemGroup>
</Project>