namespace SocketLabs.InjectionApi.Core.Serialization
{
    /// <summary>
    /// Data transfer object representing the Injection Api response.
    /// </summary>
    internal class InjectionResponseDto
    {
        /// <summary>
        /// The resulting response ErrorCode of the Injection Api send request
        /// </summary>
        public string ErrorCode { get; set; }

        /// <summary>
        /// A unique key generated by the Injection API if an unexpected error occurs during the SocketLabsClient send request.
        /// This unique key can be used by SocketLabs support to troubleshoot the issue.
        /// </summary>
        public string TransactionReceipt { get; set; }

        /// <summary>
        /// An array of MessageResultDto objects that contain the status of each message sent.
        /// </summary>
        public MessageResultDto[] MessageResults { get; set; }
    }
}